### ISSUE TITLE
Different executors can share the same display

### ISSUE THREAD

**Issue by MarkZ3** [hudson3-plugins/xvnc-plugin#1]
I noticed something interesting while looking at the console logs that could explain some of our build failures. It seems that sometimes, 2 Hudson executors can share the same display which seems like a bug in the Hudson Xvnc plugin. For example,

https://hudson.eclipse.org/linuxtools/job/linuxtools-gerrit/9140/consoleFull
and
https://hudson.eclipse.org/linuxtools/job/linuxtools-gerrit/9141/consoleFull

They were running at the same time. In build #9140, the display was :76
...
[workspace_3] $ Xvnc :76 -geometry 1024x768 -depth 24 -ac
...

In the build #9141, the same command is executed but with error:

[workspace] $ Xvnc :76 -geometry 1024x768 -depth 24 -ac
Fatal server error:
Server is already active for display 76
        If this server is no longer running, remove /tmp/.X76-lock
        and start again.

At the end of both console log, I can see that they ended up both using the same display:
Xlib:  extension "RANDR" missing on display ":76.0".

Also, I have found somewhat similar bug report in Jenkins here: https://issues.jenkins-ci.org/browse/JENKINS-17550
With the fix here: https://github.com/jenkinsci/xvnc-plugin/commit/6bdd6098c1d5f2a5aeb52fd05fa2f82d85782f96

Would it be possible/accceptable to port the fix from the Jenkins version of the plugin?

**Comment by wjprakash** [comment]
Sure we will port the bug fix

**Comment by MarkZ3** [comment]
That's great to hear! Has there been any progress? Let me know if I can help!

**Comment by bobfoster** [comment]
Just started on it. Looks easy enough.

On Wed, Nov 5, 2014 at 7:42 AM, Marc-Andre Laperle <notifications@github.com

**Comment by MarkZ3** [comment]
I also noticed there was a subsequent fix related to this problem:
https://github.com/jenkinsci/xvnc-plugin/commit/3627859ad1076ed279b1b731f2fb009a58cca368

**Comment by bobfoster** [comment]
Right. You want an allocator per node, not a global allocator.

On Wed, Nov 5, 2014 at 1:49 PM, Marc-Andre Laperle <notifications@github.com

**Comment by bobfoster** [comment]
Filed this bug so I can track my bugs in the same place.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=450388
